CREATE TABLE ANALISTA (
  idANALISTA INTEGER NOT NULL,
  idUSUARIO INTEGER NOT NULL,
  NIVEL_ANALISTA INTEGER not NULL,
  NOME VARCHAR2(50) not NULL,
  LOGIN VARCHAR2(10),
  SENHA VARCHAR2(15),
  PERMISSAO VARCHAR2(20),
  PRIMARY KEY(idANALISTA));
  
 
  
  CREATE TABLE CATEGORIA (
  idCATEGORIA INTEGER NOT NULL ,
  CATEGORIA VARCHAR2(20) NULL,
  PRIMARY KEY(idCATEGORIA));
   COMMIT;
  
 
CREATE TABLE DEPARTAMENTO (
  idDEPART INTEGER NOT NULL ,
  DEPARTAMENTO VARCHAR2(20) NULL,
  PRIMARY KEY(idDEPART));
   COMMIT;
   

CREATE TABLE PRIORIDADE (
  idPRIORIDADE INTEGER NOT NULL ,
  PRIORIDADE VARCHAR2(10) NULL,
  PRIMARY KEY(idPRIORIDADE));
    COMMIT; 

CREATE TABLE TICKET (
  idTICKET INTEGER NOT NULL ,
  idTIPO INTEGER NOT NULL,
  idPRIORIDADE INTEGER NOT NULL,
  idUSUARIO INTEGER NOT NULL,
  idANALISTA INTEGER NOT NULL,
  idCATEGORIA INTEGER NOT NULL, 
  USUARIO VARCHAR2(50),
  TIPO VARCHAR2(20),
  CATEGORIA VARCHAR2(15),
  ASSUNTO VARCHAR2(100),
  DESCRICAO VARCHAR2(255),
  SOLUCAO VARCHAR2(255),
  NIVEL_ANALISTA INTEGER,
  ANALISTA VARCHAR2(50),
  DATA_INICIO DATE,
  DATA_FIM DATE,
  STATUS VARCHAR2(15),
  PRIMARY KEY(idTICKET));
   COMMIT;

  CREATE TABLE TIPO_TICKET (
  idTIPO INTEGER NOT NULL ,
  TIPO VARCHAR2(15),
  PRIMARY KEY(idTIPO));
   COMMIT;

CREATE TABLE USUARIO (
  idUSUARIO INTEGER NOT NULL ,
  idDEPART INTEGER NOT NULL,
  PERMISSAO VARCHAR2(20) NOT NULL,
  NOME VARCHAR2(50) NOT NULL,
  DEPARTAMENTO VARCHAR2(20) NOT NULL,
  SEXO VARCHAR2(1),
  EMAIL VARCHAR2(50),
  ISANALISTA CHAR(1) NOT NULL,
  NIVEL_ANALISTA INTEGER,
  LOGIN VARCHAR2(15),
  SENHA VARCHAR2(10),
  PRIMARY KEY(idUSUARIO));
 COMMIT;
 
CREATE TABLE LOGIN(
IDLOGIN INTEGER,
IDANALISTA INTEGER,
LOGIN VARCHAR(10),
SENHA VARCHAR(10),
PERMISSAO VARCHAR2(20),
PRIMARY KEY (IDLOGIN));
COMMIT;

CREATE TABLE RELATORIO(
IDRELATORIO INTEGER ,
IDTICKET INTEGER ,
TIPO VARCHAR2(20) ,
CATEGORIA VARCHAR2(20),
ASSUNTO VARCHAR2(100),
DESCRICAO VARCHAR2(255) ,
SOLUCAO VARCHAR2(255) ,
DATA_INICIO DATE,
DATA_FIM DATE ,
STATUS VARCHAR2(10));


-- ALTER TABLES PARA ADICIONAR AS FOREING KEYS
ALTER TABLE RELATORIO
ADD CONSTRAINT FK_IDTICKET_REL
FOREIGN KEY (IDTICKET)
REFERENCES TICKET(IDTICKET)
ON DELETE CASCADE ;

ALTER TABLE TICKET
ADD CONSTRAINT FK_TIPOO
FOREIGN KEY (idTIPO)
REFERENCES TIPO_TICKET(idTIPO)
ON DELETE CASCADE ;

ALTER TABLE TICKET
ADD CONSTRAINT FK_PRIORIDADE
FOREIGN KEY (idPRIORIDADE)
REFERENCES PRIORIDADE(idPRIORIDADE)
ON DELETE CASCADE ;

ALTER TABLE TICKET
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO)
ON DELETE CASCADE ;

ALTER TABLE TICKET
ADD CONSTRAINT FK_ANALISTA
FOREIGN KEY (IDANALISTA)
REFERENCES ANALISTA(IDANALISTA)
ON DELETE CASCADE ;

ALTER TABLE TICKET
ADD CONSTRAINT FK_CATEGORIA
FOREIGN KEY (idCATEGORIA)
REFERENCES CATEGORIA(idCATEGORIA)
ON DELETE CASCADE;

ALTER TABLE LOGIN
ADD CONSTRAINT FK_LOGIN1
FOREIGN KEY (IDANALISTA)
REFERENCES ANALISTA(IDANALISTA)
ON DELETE CASCADE ;




ALTER TABLE ANALISTA
ADD CONSTRAINT FK_USER_ANALISTA
FOREIGN KEY (IDUSUARIO)
REFERENCES USUARIO(IDUSUARIO)
ON DELETE CASCADE ;

COMMIT;

--SEQUENCES

CREATE SEQUENCE CONT_IDANALISTA NOCACHE;

CREATE SEQUENCE CONT_IDLOGIN NOCACHE;
CREATE SEQUENCE CONT_IDTICKET NOCACHE;
 create sequence CONT_IDUSUARIO

increment by 1

start with 1

maxvalue 999

nocycle;
 COMMIT;

--TRIGGER PARA SALVAR NA TABELA RELATORIO 
create or replace TRIGGER TICKET_REL AFTER INSERT ON TICKET
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW
BEGIN
INSERT INTO RELATORIO (IDTICKET,TIPO, CATEGORIA, ASSUNTO, DESCRICAO,SOLUCAO, DATA_INICIO, DATA_FIM, STATUS)
VALUES (:NEW.IDTICKET,:NEW.TIPO, :NEW.CATEGORIA, :NEW.ASSUNTO, :NEW.DESCRICAO, :NEW.SOLUCAO ,  :NEW.DATA_INICIO, :NEW.DATA_FIM, :NEW.STATUS);
END;


--EXECUTE UMA TRIGGER DE CADA VEZ SE NAAO AO CRIAR A PRIMEIRA TRIGGER A TRIGGER SEGUINTE IRA PARA DENTRO DA MESMA OCASIONANDO O ERRO 


create or replace TRIGGER UPDATE_REL AFTER UPDATE ON TICKET
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW
BEGIN
UPDATE RELATORIO SET TIPO = :NEW.TIPO, CATEGORIA = :NEW.CATEGORIA, ASSUNTO = :NEW.ASSUNTO,DESCRICAO = :NEW.DESCRICAO,SOLUCAO = :NEW.SOLUCAO,DATA_FIM = :NEW.DATA_FIM ,STATUS = :NEW.STATUS WHERE IDTICKET = :NEW.IDTICKET;
END;


--EXECUTE UMA TRIGGER DE CADA VEZ SE NAAO AO CRIAR A PRIMEIRA TRIGGER A TRIGGER SEGUINTE IRA PARA DENTRO DA MESMA OCASIONANDO O ERRO 
--EXECUTE UMA TRIGGER DE CADA VEZ SE NAAO AO CRIAR A PRIMEIRA TRIGGER A TRIGGER SEGUINTE IRA PARA DENTRO DA MESMA OCASIONANDO O ERRO 


CREATE OR REPLACE TRIGGER ADD_ANALISTA AFTER INSERT ON USUARIO
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW

BEGIN
IF :NEW.ISANALISTA = 'S'  THEN
 INSERT INTO  ANALISTA  (IDANALISTA,IDUSUARIO,NIVEL_ANALISTA,NOME,LOGIN,SENHA,PERMISSAO)
VALUES(CONT_IDANALISTA.NEXTVAL,:NEW.IDUSUARIO,:NEW.NIVEL_ANALISTA,:NEW.NOME,:NEW.LOGIN,:NEW.SENHA,:NEW.PERMISSAO);

end if;
END ADD_ANALISTA;


--EXECUTE UMA TRIGGER DE CADA VEZ SE NAAO AO CRIAR A PRIMEIRA TRIGGER A TRIGGER SEGUINTE IRA PARA DENTRO DA MESMA OCASIONANDO O ERRO 


CREATE OR REPLACE TRIGGER ADD_LOGIN AFTER INSERT ON ANALISTA
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW

BEGIN
 INSERT INTO  LOGIN  (IDLOGIN,IDANALISTA,LOGIN,SENHA,PERMISSAO)
VALUES(CONT_IDLOGIN.NEXTVAL,:NEW.IDANALISTA,:NEW.LOGIN,:NEW.SENHA,:NEW.PERMISSAO);


END ADD_LOGIN;
--EXECUTE A INSTRUA‡AAO DA TRIGGER SOZINHA
--EXECUTE A INSTRUA‡AAO DA TRIGGER SOZINHA
--EXECUTE A INSTRUA‡AAO DA TRIGGER SOZINHA
create or replace TRIGGER UPDATE_ANALISTA AFTER update ON USUARIO
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW

BEGIN

 UPDATE ANALISTA  SET NIVEL_ANALISTA = :NEW.NIVEL_ANALISTA, LOGIN = :NEW.LOGIN, SENHA  = :NEW.SENHA ,PERMISSAO = :NEW.PERMISSAO WHERE IDUSUARIO = :NEW.IDUSUARIO;


END UPDATE_ANALISTA;
--EXECUTE A INSTRUA‡AAO DA TRIGGER SOZINHA
--EXECUTE A INSTRUA‡AAO DA TRIGGER SOZINHA
--EXECUTE A INSTRUA‡AAO DA TRIGGER SOZINHA

create or replace TRIGGER UPDATE_LOGIN AFTER update ON ANALISTA
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW

BEGIN

 UPDATE LOGIN   SET LOGIN = :NEW.LOGIN, SENHA  = :NEW.SENHA ,PERMISSAO = :NEW.PERMISSAO WHERE IDANALISTA = :NEW.IDANALISTA;

END UPDATE_LOGIN;

-- EXECUTE A TRIGGER ACIMA SOZINHA SE NAAO VAI DAR ERRO


-- STORED PROCEDURES
-- STORED PROCEDURES
-- STORED PROCEDURES
create or replace PROCEDURE GERA_REL
(
status_rel IN VARCHAR2,
CURSOR_OUT OUT sys_refcursor
)
IS
BEGIN
OPEN CURSOR_OUT FOR
 SELECT TIPO, CATEGORIA, ASSUNTO, DESCRICAO ,SOLUCAO, DATA_INICIO , DATA_FIM FROM  RELATORIO WHERE STATUS = status_rel ;
END;


-- funA§A£o
-- funA§A£o

create or replace FUNCTION RETORNA_DIAS
RETURN sys_refcursor
AS
MYCURSOR sys_refcursor;
BEGIN
OPEN MYCURSOR FOR

 select IDTICKET,USUARIO,TIPO,CATEGORIA,ASSUNTO,DESCRICAO,DATA_INICIO, sysdate - DATA_INICIO  as DIFERENCA_DATAS   from TICKET WHERE STATUS = 'ABERTO' ORDER BY DIFERENCA_DATAS ASC;
RETURN MYCURSOR;
END;


----
create or replace FUNCTION RETORNA_DIAS_FECHADOS
RETURN sys_refcursor
AS
MYCURSOR sys_refcursor;
BEGIN
OPEN MYCURSOR FOR

 select IDTICKET,USUARIO,TIPO,CATEGORIA,ASSUNTO,DESCRICAO,DATA_INICIO,DATA_FIM, sysdate - DATA_FIM  as DIFERENCA_DATAS   from TICKET WHERE STATUS = 'FECHADO' ORDER BY DIFERENCA_DATAS ASC;
RETURN MYCURSOR;
END;




--INSERTS PARA POPULAR AS TABELAS

INSERT INTO TIPO_TICKET VALUES (0001,'PROBLEMA');
INSERT INTO TIPO_TICKET VALUES (0002,'DUVIDA');
INSERT INTO TIPO_TICKET VALUES (0003,'SOLICITACAO');
  
    
INSERT INTO PRIORIDADE VALUES (0001,'ALTA');
INSERT INTO PRIORIDADE VALUES (0002,'MEDIA');
INSERT INTO PRIORIDADE VALUES (0003,'BAIXA');
  
INSERT INTO DEPARTAMENTO VALUES (0001,'RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTO VALUES (0002,'FINANCEIRO');
INSERT INTO DEPARTAMENTO VALUES (0003,'COMERCIAL');
INSERT INTO DEPARTAMENTO VALUES (0004,'MARKETING');
INSERT INTO DEPARTAMENTO VALUES (0005,'CONTROLADORIA');
INSERT INTO DEPARTAMENTO VALUES (0006,'LOGISTICA');
INSERT INTO DEPARTAMENTO VALUES (0007,'DIRETORIA');
INSERT INTO DEPARTAMENTO VALUES (0008,'TI');
   
  
INSERT INTO CATEGORIA VALUES (0001,'HARDWARE');
INSERT INTO CATEGORIA VALUES (0002,'SOFTWARE');
INSERT INTO CATEGORIA VALUES (0003,'REDES');
INSERT INTO CATEGORIA VALUES (0004,'TELEFONIA');
INSERT INTO CATEGORIA VALUES (0005,'EMAIL');
  

  
-- INSERE USUARIOS


INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,1,'NAO POSSUE','DIEGO ALEX','RECURSOS HUMANOS','M','DIEGO.ALEX@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,8,'ADMINISTRADOR','TIAGO CARDOSO','TI','M','TIAGO.CARDOSO@HELPDESK.COM','S','2','TCARDOSO','1234');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,8,'ADMINISTRADOR','WELLINGTON ALVES','TI','M','WELLINGTON ALVES@HELPDESK.COM','S','2','WALVES','1234');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,8,'ADMINISTRADOR','FERNANDO MEDINA','TI','M','FERNANDO.MEDINAX@HELPDESK.COM','S','2','FMEDINA','1234');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,2,'NAO POSSUE','LEONARDO CARDOSO','FINANCEIRO','M','LEONARDO.CARDOSO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,3,'NAO POSSUE','ANDREZA SAFADA','COMERCIAL','F','ANDREZA.SAFADA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,1,'NAO POSSUE','THOMAS ALBERTO','RECURSOS HUMANOS','M','THOMAS.ALBERTO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,1,'NAO POSSUE','ABRAAAO MUNHOS','RECURSOS HUMANOS','M','ABRAAAO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,2,'NAO POSSUE','TATIANE MUNIZ','FINANCEIRO','F','TATIANE.MUNIZ@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,2,'NAO POSSUE','INDIANO ALBERTO','FINANCEIRO','M','INDIANO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,4,'NAO POSSUE','CLAUDIO MARZO ALEX','MARKETING','M','CLAUDIO.MARZO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,4,'NAO POSSUE','CLAUDINEI OLIVEIRA','MARKETING','M','CLAUDINEI.OLIVEIRA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,4,'NAO POSSUE','PAOLA OLIVEIRA','MARKETING','F','PAOLA.OLIVEIRA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,4,'NAO POSSUE','ALINE RISCADO','MARKETING','F','ALINE.RISCADO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,4,'NAO POSSUE','ALLAN WOLF','MARKETING','M','ALLAN.WOLF@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,8,'ANALISTA','DILMA ROUSEFFU','TI','F','OOODILMAAAA@HELPDESK.COM','S','1','TQUERIDA','1234');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'ANALISTA','MICHEL TEMER','TI','M','TEMER@HELPDESK.COM','S','1','FALGO','1234');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'NAO POSSUE','BARROSO','CONTROLADORIA','M','BARROSO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'NAO POSSUE','SASHA MENEGUEL','CONTROLADORIA','F','MENEGUEL@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'NAO POSSUE','JULIANA PAES','CONTROLADORIA','F','JULIANA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'NAO POSSUE','CONNOR MACGRAGOR','CONTROLADORIA','M','CONNOR@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'NAO POSSUE','MASSARANDUMA','CONTROLADORIA','M','MASSARANDUMA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,5,'NAO POSSUE','SONIA BRAGA','CONTROLADORIA','F','BRAGA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,6,'NAO POSSUE','SEBASTIAAO SILVA','LOGISTICA','M','SEBASTIAAO.SILVA@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,6,'NAO POSSUE','AMERICO TORRES','LOGISTICA','M','AMERICO.TORRES@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,6,'NAO POSSUE','ORACY MARTOS','LOGISTICA','M','ORACIO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,7,'NAO POSSUE','FREDERICO SOUZA','DIRETORIA','M','FRED@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,7,'NAO POSSUE','ORACY MARTOS','DIRETORIA','M','ORACIO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,7,'NAO POSSUE','FREDERICO SOUZA','DIRETORIA','M','FRED@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,7,'NAO POSSUE','ORACY MARTOS','DIRETORIA','M','ORACIO@HELPDESK.COM','N','0','NAO POSSUE','NAO POSSUE');
INSERT INTO USUARIO VALUES (CONT_IDUSUARIO.NEXTVAL,8,'ADMINISTRADOR','ADMINISTRADOR','TI','M','ADMINISTRADOR@HELPDESK.COM','S','2','ADMIN','ADMIN');


  
--IDTICKET,IDTIPO, IDPRIORI, IDUUARIO,IDANALIST, IDCATEGORIA,

INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,1,1,2,'DIEGO ALEX', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,12,1,2,'CLAUDIO MARZO ALEX', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');



INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,1,25,3,2,'SEBASTIAAO SILVA', 'PROBLEMA', 'HARDWARE','PLACA DE VIDEO','SUBSTITIUCAO DA PLACA DE VIDEO','A PREENCHER',2,'WELLINGTON ALVES','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,26,1,2,'AMERICO TORRES', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,3,10,1,2,'INDIANO ALBERTO', 'PROBLEMA', 'REDES','USUARIO SEM CONEXAAO DE REDE','CONFIGURAA‡AAO DE REDE NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,30,1,2,'ORACY MARTOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,29,1,2,'FREDERICO SOUZA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,8,1,2,'ABRAAAO MUNHOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,9,1,2,'TATIANE MUNIZ', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,7,1,2,'THOMAS ALBERTO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,6,1,2,'ANDREZA SAFADA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'LEONARDO CARDOSO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,1,1,2,'DIEGO ALEX', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,12,1,2,'CLAUDIO MARZO ALEX', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','INSTALACAO BEM SUCEDIDA',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,1,25,3,2,'SEBASTIAAO SILVA', 'PROBLEMA', 'HARDWARE','PLACA DE VIDEO','SUBSTITIUCAO DA PLACA DE VIDEO','SUBSTITIUCAO BEM SUCEDIDA',2,'WELLINGTON ALVES','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,26,1,2,'AMERICO TORRES', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,3,10,1,2,'INDIANO ALBERTO', 'PROBLEMA', 'REDES','USUARIO SEM CONEXAAO DE REDE','CONFIGURAA‡AAO DE REDE NA MAQUINA DO USUARIO','CONFIGURAA‡AAO BEM SUCEDIDA',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,30,1,2,'ORACY MARTOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,29,1,2,'FREDERICO SOUZA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,8,1,2,'ABRAAAO MUNHOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,9,1,2,'TATIANE MUNIZ', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,7,1,2,'THOMAS ALBERTO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,6,1,2,'ANDREZA SAFADA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'LEONARDO CARDOSO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'LEONARDO CARDOSO', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'FREDERICO SOUZA', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','20-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'ORACY MARTOS', 'PROBLEMA', 'EMAIL','EMAIL NAO ENVIA/RECEBE NOVA MENSAGENS','FUCIONARIO INFOMRA QUE SEU EMAIL NAO ESTA ENVIANDO E RECEBENDO MENSAENS',' CABO DE REDE DESCONECTADO ',2,'TIAGO CARDOSO','10-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'AMERICO TORRES', 'PROBLEMA', 'REDES','WIFI NAO CONECTA','ROTEADOR WIFI ESTA COM ERRO',' RESTART DO ADAPTADOR DE REDE ',2,'TIAGO CARDOSO','10-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'AMERICO TORRES', 'PROBLEMA', 'HARDWARE','PLACA DE VIDEO','VIDEO FALHANDO',' PLACA DE VIDEO SUBSTITUIDA ',2,'TIAGO CARDOSO','09-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'SEBASTIAAO SILVA', 'PROBLEMA', 'HARDWARE','FALHA NO AUDIO','AUDIO DO PC NAAO ESTA� FUNCIONANDO CORRETAMENTE',' SUBSTITUIDA A CAIXA DE SOM ',2,'TIAGO CARDOSO','09-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'THOMAS ALBERTO', 'PROBLEMA', 'SOFTWARE','ERRO DE CERTIFICADO DIGITAL','CERTIFICADO DIGITAL COM ERRO',' INSTALADO NOVA VERSAAO DO CERTIFICADO DIGITAL',2,'TIAGO CARDOSO','30-04-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'THOMAS ALBERTO', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','20-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'FREDERICO SOUZA', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','20-05-16','FECHADO');

INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,1,25,3,2,'LEONARDO CARDOSO', 'PROBLEMA', 'HARDWARE','PLACA DE VIDEO','SUBSTITIUCAO DA PLACA DE VIDEO','A PREENCHER',2,'WELLINGTON ALVES','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,26,1,2,'AMERICO TORRES', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,3,10,1,2,'INDIANO ALBERTO', 'PROBLEMA', 'REDES','USUARIO SEM CONEXAAO DE REDE','CONFIGURAA‡AAO DE REDE NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,30,1,2,'ORACY MARTOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,29,1,2,'FREDERICO SOUZA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,8,1,2,'ABRAAAO MUNHOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,9,1,2,'TATIANE MUNIZ', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,7,1,2,'THOMAS ALBERTO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,6,1,2,'ANDREZA SAFADA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'LEONARDO CARDOSO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','16-05-16','16-05-16','ABERTO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,1,1,2,'DIEGO ALEX', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','A PREENCHER',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,12,1,2,'CLAUDIO MARZO ALEX', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','INSTALACAO BEM SUCEDIDA',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,1,25,3,2,'SEBASTIAAO SILVA', 'PROBLEMA', 'HARDWARE','PLACA DE VIDEO','SUBSTITIUCAO DA PLACA DE VIDEO','SUBSTITIUCAO BEM SUCEDIDA',2,'WELLINGTON ALVES','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,26,1,2,'AMERICO TORRES', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,3,10,1,2,'INDIANO ALBERTO', 'PROBLEMA', 'REDES','USUARIO SEM CONEXAAO DE REDE','CONFIGURAA‡AAO DE REDE NA MAQUINA DO USUARIO','CONFIGURAA‡AAO BEM SUCEDIDA',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,30,1,2,'ORACY MARTOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,29,1,2,'FREDERICO SOUZA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,8,1,2,'ABRAAAO MUNHOS', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,9,1,2,'TATIANE MUNIZ', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,7,1,2,'LEONARDO CARDOSO', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,6,1,2,'ANDREZA SAFADA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'ANDREZA SAFADA', 'PROBLEMA', 'SOFTWARE','GOOGLE CHROME INSTALATION','INSTALACAO DO GOOGLE CHROME NA MAQUINA DO USUARIO','GOOGLE CHROME INSTALADO',2,'TIAGO CARDOSO','01-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'LEONARDO CARDOSO', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'FREDERICO SOUZA', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','20-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'ORACY MARTOS', 'PROBLEMA', 'EMAIL','EMAIL NAO ENVIA/RECEBE NOVA MENSAGENS','FUCIONARIO INFOMRA QUE SEU EMAIL NAO ESTA ENVIANDO E RECEBENDO MENSAENS',' CABO DE REDE DESCONECTADO ',2,'TIAGO CARDOSO','10-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'DIEGO ALEX', 'PROBLEMA', 'REDES','WIFI NAO CONECTA','ROTEADOR WIFI ESTA COM ERRO',' RESTART DO ADAPTADOR DE REDE ',2,'TIAGO CARDOSO','10-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'DIEGO ALEX', 'PROBLEMA', 'HARDWARE','PLACA DE VIDEO','VIDEO FALHANDO',' PLACA DE VIDEO SUBSTITUIDA ',2,'TIAGO CARDOSO','09-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'DIEGO ALEX', 'PROBLEMA', 'HARDWARE','FALHA NO AUDIO','AUDIO DO PC NAAO ESTA� FUNCIONANDO CORRETAMENTE',' SUBSTITUIDA A CAIXA DE SOM ',2,'TIAGO CARDOSO','09-05-16','15-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'DIEGO ALEX', 'PROBLEMA', 'SOFTWARE','ERRO DE CERTIFICADO DIGITAL','CERTIFICADO DIGITAL COM ERRO',' INSTALADO NOVA VERSAAO DO CERTIFICADO DIGITAL',2,'TIAGO CARDOSO','30-04-16','01-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'DIEGO ALEX', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','20-05-16','FECHADO');
INSERT INTO TICKET VALUES (CONT_IDTICKET.NEXTVAL,1,2,5,1,2,'ORACY MARTOS', 'SOLICITACAO', 'SOFTWARE','INSTALAR O DRIVE DE REDE','FUCIONARIO SOLICITA A INSTALACAO DO DRIVE DE REDE EM SUA MAQUINA','DRIVE INSTALADO CORRETAMENTE',2,'TIAGO CARDOSO','10-05-16','20-05-16','FECHADO');

COMMIT;


 



--******************** NAAO EXECUTAR DAQUI PRA BAIXO*************************************






DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE ANALISTA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE TIPO_TICKET CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE PRIORIDADE CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE RELATORIO CASCADE CONSTRAINTS;
DROP TABLE LOGIN CASCADE CONSTRAINTS;
DROP SEQUENCE CONT_IDANALISTA;
DROP SEQUENCE CONT_IDLOGIN;
DROP SEQUENCE CONT_IDUSUARIO;
DROP SEQUENCE CONT_IDTICKET;
DROP PROCEDURE gera_rel;
DROP FUNCTION RETORNA_DIAS;
DROP TRIGGER TICKET_REL;
DROP TRIGGER ADD_LOGIN;
DROP TRIGGER ADD_ANALISTA;
COMMIT;




--SELECT PARA BUSCAR O USUARIO PARA LOGIN
SELECT * FROM LOGIN WHERE PERMISSAO = 'ADMINISTRADOR' AND PERMISSAO = 'ANALISTA';